CREATE DATABASE IF NOT EXISTS DBUnit;
USE DBUnit;
CREATE TABLE IF NOT EXISTS Alumnos(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(40) NOT NULL,
  email VARCHAR(40) NOT NULL,
  edad INT NOT NULL,
  promedio FLOAT NOT NULL
);
